openapi: 3.0.0
info:
  title: Booking API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
paths:
  /bookings:
    get:
      summary: Returns a list of bookings.
      description: Optional extended description in CommonMark or HTML.
      responses:
        200:
          description: A list of bookings
          content:
            application/json:
              schema:
                $ref: '#/definitions/Booking'
definitions:
  Booking:
    type: object
    properties:
      start_time:
        type: string
      end_time:
        type: string
